export const surveyJson = {
  pages: [{
    elements: [{
      type: "html",
      html: "<h2>Teste de Temperamento."
    }]
  }, {
    elements: [{
      name: "Temperamento Sanguíneo",
      title: "Selecione:",
      type: "checkbox",
      choices: [
        "Despreocupado(a)",
        "Calmo(a)",
        "Animado(a)",
        "Jovial",
        "Sociável",
        "Simpático(a)",
        "Loquaz {Fala muito}",
        "Age rápido",
        "Workaholic {Viciado(a) em trabalho}",
        "Tagarela {Conversador(a)}",
        "Eloquente {Expressa-se bem}",
        "Superficial {Não aprofunda-se}",
        "Expansivo(a) {Demonstra emoções abertamente}",
        "Falante {Comunicativo(a)}",
        "Amigável",
        "Adaptável",
        "Pitoresco(a) {Peculiar}",
        "Brilhante",
        "Impaciente",
        "Irresponsável {Inconsequente}",
        "Não confiável {Inseguro}",
        "Fugidio {Difícil de compreender}",
        "Flexível",
        "Generoso(a)",
        "Levanta-se cedo",
        "Volúvel {Inconstante}",
        "Feliz"
      ],
      "isRequired": false,
      "colCount": 2
      // "showNoneItem": true,
      // "showOtherItem": true,
      // "showSelectAllItem": true,
      // "separateSpecialChoices": true
    }]
  }, {
    elements: [{
      name: "Temperamento Colérico",	
      title: "Selecione:",
      type: "checkbox",
      choices: [
        "Impulsivo(a)",
        "Irrequieto(a) {Inquieto(a)}",
        "Esquentado(a)",
        "Ativo(a)",
        "Excitável {Agitado(a)}",
        "Corado(a)",
        "Um(a) líder",
        "Agressivo(a)",
        "Convincente",
        "Cheio de energia",
        "Extrovertido(a)",
        "Turbulento(a) {Agitado(a)}",
        "Impaciente",
        "Empreendedor(a)",
        "Pioneiro(a)",
        "Barulhento(a)",
        "Prático(a)",
        "Dramático(a)",
        "Esquecido(a)",
        "Esportivo(a)",
        "Competitivo(a)",
        "Resistente",
        "Dominador(a)",
        "Intolerante",
        "Obstinado(a)",
        "Irascível {Irritável}",
        "Audaz {Corajoso(a)}"
      ],
      "isRequired": false,
      "colCount": 2
      // "showNoneItem": true,
      // "showOtherItem": true,
      // "showSelectAllItem": true,
      // "separateSpecialChoices": true
    }]
  }, {
    elements: [{
      name: "Temperamento Melancólico",
      title: "Selecione:",
      type: "checkbox",
      choices: [
        "Pessimista",
        "Melancólico(a)",
        "Amuado(a)",
        "Sóbrio(a) {Sério(a)}",
        "Nervoso(a) {Ansioso(a)}",
        "Distante",
        "Quieto(a)",
        "Reservado(a)",
        "Resignado(a) {Aceita o que não pode mudar}",
        "Triste",
        "Inconsolável {Não consegue se sentir melhor}",
        "Desanimado(a)",
        "Pensativo(a)",
        "Introspectivo(a) {Reflexivo(a)}",
        "Egoísta {Egocêntrico(a)}",
        "Exigente",
        "Suscetível {Sensível}",
        "Leitor(a)",
        "Lento(a)",
        "Tristonho(a)",
        "Taciturno(a) {Silencioso(a)}",
        "Intelectual",
        "Boa memória",
        "Observador(a)",
        "Ingrato(a)",
        "Insatisfeito(a)",
        "Abnegado(a) {Desinteressado(a)}",
      ],
      "isRequired": false,
      "colCount": 2
      // "showNoneItem": true,
      // "showOtherItem": true,
      // "showSelectAllItem": true,
      // "separateSpecialChoices": true
    }]
  },
  {
    elements: [{
      name: "Temperamento Fleumático",
      title: "Selecione:",
      type: "checkbox",
      choices: [
        "Cuidadoso(a)",
        "Metódico(a) {Organizado(a)}",
        "Estável(a) {Constante}",
        "Passivo(a) {Inativo(a)}",
        "Pacato(a) {Tranquilo(a)}",
        "Pensativo(a)",
        "Calmo(a)",
        "Controlado(a)",
        "Folgado(a) {Preguiçoso(a)}",
        "Plácido(a) {Tranquilo(a)}",
        "Sem pressa",
        "Lento(a)",
        "Implacável {Persistente}",
        "Comedido(a) {Moderado(a)}",
        "Tranquilo(a)",
        "Ensimesmado(a) {Reflexivo(a)}",
        "Reservado(a)",
        "Sonhador(a)",
        "Gosta de Rotina",
        "Lento(a) para aprender",
        "Perseverante",
        "Obstinado(a) {Teimoso(a)}",
        "Tímido(a)",
        "Constante",
        "Sensato(a)",
        "Indiferente",
        "Apático(a) {Desinteressado(a)}",
      ],
      "isRequired": false,
      "colCount": 2
      // "showNoneItem": true,
      // "showOtherItem": true,
      // "showSelectAllItem": true,
      // "separateSpecialChoices": true
    }]
  }],
  showQuestionNumbers: "on",
  pageNextText: "Seguinte",
  pagePrevText: "Anterior",
  completeText: "Enviar",
  showPrevButton: true,
  firstPageIsStarted: true,
  startSurveyText: "Iniciar",
  completedHtml: "Obrigada!",
  // showPreviewBeforeComplete: "showAnsweredQuestions"
};
